name: dpmssurveyapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  arcgis_maps: ^200.8.0+4672
  file_picker: ^10.3.2
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.0
  flutter_image_compress: ^2.4.0
  cupertino_icons: ^1.0.8
  arcgis_maps_toolkit: ^200.8.0+4672
  shared_preferences: ^2.5.3
  path: ^1.9.0
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/waterdrop_mobile.jpg
